name: UI CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui/app/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Build
        run: npm run build -- --configuration=production

      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ui-build
          path: ui/app/dist/
          retention-days: 7
