name: UI CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui/app/package-lock.json'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration=production

      - name: Test
        run: npm run test:ci

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ui/app/test-results/
          retention-days: 7

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()  # Always run even if the previous steps fail
        with:
          report_paths: 'ui/app/test-results/test-results.xml'
          fail_on_failure: true
          check_name: 'UI Test Results'

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: ui/app/dist/
          retention-days: 7
