name: UI CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ui/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'ui/app/package-lock.json'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: npm ci

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Build
        run: npm run build -- --configuration=production

      - name: Test with detailed output
        run: |
          echo "Running tests with JUnit reporter..."
          npm run test:ci
        continue-on-error: true

      - name: Debug file system
        if: always()
        run: |
          echo "Current directory structure:"
          pwd
          find . -type d -maxdepth 3
          
          echo -e "\nSearching for any XML files:"
          find . -name "*.xml" || echo "No XML files found"
          
          echo -e "\nListing test-results directory (if exists):"
          if [ -d "test-results" ]; then
            ls -la test-results/
          else
            echo "test-results directory not found"
          fi
          
          echo -e "\nChecking for files in current directory:"
          ls -la

      - name: Upload test results (from root)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-root
          path: ui/app/*.xml
          if-no-files-found: warn
          retention-days: 7

      - name: Upload test results (from test-results dir)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-dir
          path: ui/app/test-results/
          if-no-files-found: warn
          retention-days: 7

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: ui/app/dist/
          retention-days: 7
